# Workflow trigger on any push and pull request
name: Workflow for push and PR

on:
  [push, pull_request]

defaults:
  run:
    working-directory: packages/design-system

# Job will run on a ubuntu instance
jobs:
  build-design-system:
    uses: ./.github/workflows/integration-tests-command.yml
    name: build-design-system
